title: Zongliang Nan's Homepage
page-top-title: Zongliang Nan
top-section-bg-text: Be what you wanna be
home-subtitle: Zongliang Nan&ensp;|&ensp;南宗良
copyright-text: '&copy; Zongliang Nan. All Rights Reserved.'
